---
driver:
  name: vagrant
  customize:
   natdnshostresolver1: "on"

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7.3

suites:
  - name: default
    run_list: recipe[fake::default]
    attributes:
