---
driver:
  name: vagrant
  customize:
   natdnshostresolver1: "on"

provisioner:
  name: chef_zero
  data_path: test/shared

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7.3
  - name: rhel-7.3
  - name: sl-6.64
    box: sl6-64-lyte
    box_url: http://lyte.id.au/vagrant/sl6-64-lyte.box

suites:
  - name: default
    run_list: recipe[fake::default]
    data_bags_path: "test/fixtures/data_bags"
    attributes:
